#!/usr/bin/env python3
"""
export_obsidian.py — Phase 5: Export analysis artifacts to an Obsidian vault.

Usage:
  python export_obsidian.py <workdir> --vault <vault_root> [--notes-dir <rel_path>] [--attachments-dir <rel_path>]

Vault resolution:
  1. --vault command line argument (highest priority)
  2. BILIBILI_ANALYZE_VAULT environment variable
  If neither is provided, the script prints an error and exits.

Defaults:
  --notes-dir        bilibili-notes
  --attachments-dir  bilibili-attachments

What it does:
  1. Copies analysis.html and thumbnail to the attachments directory.
  2. Copies screenshot slices (if present) to the attachments directory.
  3. Generates a well-structured Obsidian .md note with YAML frontmatter and embeds.
"""
import argparse, json, os, shutil, sys
from pathlib import Path
from datetime import datetime


def slugify(text: str, max_len: int = 40) -> str:
    """Derive a safe file-name slug from a video title."""
    keep = []
    for ch in text[:max_len]:
        if ch.isalnum() or ch in ' _-':
            keep.append(ch)
        elif '\u4e00' <= ch <= '\u9fff' or '\u3040' <= ch <= '\u30ff':
            keep.append(ch)
    return ''.join(keep).strip().replace(' ', '_') or 'untitled'


def copy_assets(workdir: Path, att_dir: Path, slug: str) -> dict:
    """Copy HTML, thumbnail, and slices to the attachments directory."""
    att_dir.mkdir(parents=True, exist_ok=True)
    copied = {}

    html_src = workdir / "analysis.html"
    if html_src.exists():
        dst = att_dir / f"{slug}-analysis.html"
        shutil.copy2(html_src, dst)
        copied["html"] = dst
        print(f"[OK] html -> {dst}")

    for ext in ("jpg", "webp", "png"):
        thumb_src = workdir / f"thumbnail.{ext}"
        if thumb_src.exists():
            dst = att_dir / f"{slug}-thumbnail.{ext}"
            shutil.copy2(thumb_src, dst)
            copied["thumbnail"] = dst
            print(f"[OK] thumbnail -> {dst}")
            break

    # Copy full-page screenshot if present
    screenshot_src = workdir / "screenshot_full.png"
    if screenshot_src.exists():
        dst = att_dir / f"{slug}-screenshot.png"
        shutil.copy2(screenshot_src, dst)
        copied["screenshot"] = dst
        print(f"[OK] screenshot -> {dst}")

    # Copy per-section screenshots if present (generated by screenshot_sections.py / CDP)
    def _natural_key(p: Path):
        import re as _re
        return [int(t) if t.isdigit() else t for t in _re.split(r"(\d+)", p.name)]

    section_files = sorted(workdir.glob("section_*.png"), key=_natural_key)
    if section_files:
        copied_sections = []
        for src in section_files:
            dst = att_dir / f"{slug}-{src.name}"
            shutil.copy2(src, dst)
            copied_sections.append(dst)
        copied["sections"] = copied_sections
        print(f"[OK] {len(copied_sections)} section screenshots -> {att_dir}")

    slices_manifest = workdir / "slices.json"
    if slices_manifest.exists():
        with open(slices_manifest, encoding="utf-8") as f:
            manifest = json.load(f)
        copied_slices = []
        for sl in manifest.get("slices", []):
            src = workdir / sl["file"]
            if src.exists():
                dst = att_dir / f"{slug}_{sl['file']}"
                shutil.copy2(src, dst)
                copied_slices.append(dst)
        if copied_slices:
            copied["slices"] = copied_slices
            print(f"[OK] {len(copied_slices)} slices -> {att_dir}")

    return copied


def yaml_quote(value: str) -> str:
    """Quote a YAML scalar when it would otherwise be parsed as a comment or structure."""
    s = str(value).replace('"', '\\"')
    if s.startswith("#") or any(ch in s for ch in ":{}[]#,&*!|>%@`"):
        return f'"{s}"'
    return s


def yaml_tag(tag: str) -> str:
    """Obsidian tags cannot contain '#'; a leading hash is a YAML comment."""
    cleaned = str(tag).lstrip("#").strip()
    return yaml_quote(cleaned) if cleaned.startswith("#") or ":" in cleaned else cleaned


def build_frontmatter(meta: dict, state: dict) -> str:
    """Build YAML frontmatter. Use a block list so tags like #雨创计划 don't truncate the rest."""
    raw_tags = meta.get("tags") or []
    tags = [yaml_tag(t) for t in raw_tags if str(t).strip()]
    bvid = state.get("slug", "")
    lines = [
        "---",
        f'title: "{meta.get("title", "Untitled")}"',
        f"source: https://www.bilibili.com/video/{bvid}",
        f"up: {meta.get('uploader', '')}",
        f"date: {datetime.now().strftime('%Y-%m-%d')}",
        f'duration: "{meta.get("duration_string", "")}"',
        f"bv: {bvid}",
        "tags:",
    ]
    if tags:
        lines.extend(f"  - {t}" for t in tags)
    else:
        lines.append("  - 视频分析")
    lines.extend(["---", ""])
    return "\n".join(lines)


def build_note(meta: dict, state: dict, chapters: list[dict], assets: dict) -> str:
    """Build the full Obsidian Markdown note."""
    parts = [build_frontmatter(meta, state)]

    title = meta.get("title", "Untitled")
    uploader = meta.get("uploader", "")
    duration = meta.get("duration_string", "")
    bvid = state.get("slug", "")
    description = meta.get("description", "")

    parts.append(f"# {title}")
    parts.append("")
    parts.append(f'> UP主：{uploader} | 时长：{duration} | [B站原视频](https://www.bilibili.com/video/{bvid})')
    parts.append("")
    if description:
        parts.append(description)
        parts.append("")
    parts.append("---")
    parts.append("")

    # Embed full-page screenshot before chapter breakdown
    if "screenshot" in assets:
        parts.append("> [!info]- 长截图（点击展开）")
        parts.append(f"> ![[{assets['screenshot'].name}]]")
        parts.append("")
        parts.append("---")
        parts.append("")

    bvid_clean = bvid.replace("_p1", "").replace("_p2", "").replace("_p3", "")
    section_assets = assets.get("sections", [])
    for i, ch in enumerate(chapters):
        ch_title = ch.get("title", f"Chapter {i+1}")
        time_range = ch.get("time_range", "")
        start_sec = ch.get("start", 0)
        problem = ch.get("problem", "")
        steps = ch.get("steps", [])
        pitfalls = ch.get("pitfalls", [])
        conclusion = ch.get("conclusion", "")
        key_quote = ch.get("key_quote", "")

        vid_link = f"https://www.bilibili.com/video/{bvid_clean}?t={start_sec}"

        parts.append(f"## {i+1}. {ch_title} ({time_range})")
        parts.append("")
        if problem:
            parts.append(f"**核心问题**：{problem}")
            parts.append("")
        if steps:
            for s in steps:
                parts.append(f"- {s}")
            parts.append("")
        if pitfalls:
            parts.append(f"**注意陷阱**：")
            for p in pitfalls:
                parts.append(f"- ⚠ {p}")
            parts.append("")
        if conclusion:
            parts.append(f"> 💡 {conclusion}")
            parts.append("")
        if key_quote:
            parts.append(f"> 🎙 *{key_quote}*")
            parts.append("")
        # Embed matching section screenshot if available
        if i < len(section_assets):
            parts.append(f"![章节截图]({section_assets[i].name})")
            parts.append("")
        parts.append(f"[🎬 跳到此处]({vid_link})")
        parts.append("")

    parts.append("---")
    parts.append("")
    parts.append("## 📎 附件")
    parts.append("")
    if "html" in assets:
        parts.append(f"- [离线HTML笔记]({assets['html'].name})")
    if "thumbnail" in assets:
        parts.append(f"- ![封面]({assets['thumbnail'].name})")
    if "slices" in assets:
        parts.append(f"- 截图切片 ({len(assets['slices'])} 张)")
    if "sections" in assets:
        parts.append(f"- 章节截图 ({len(assets['sections'])} 张)")

    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Export bilibili-analyze output to Obsidian vault")
    parser.add_argument("workdir", help="Path to workdir (containing state.json + output files)")
    parser.add_argument("--vault", default=None, help="Obsidian vault root (or set BILIBILI_ANALYZE_VAULT)")
    parser.add_argument("--notes-dir", default="bilibili-notes", help="Relative notes directory inside vault")
    parser.add_argument("--attachments-dir", default="bilibili-attachments", help="Relative attachments directory inside vault")
    parser.add_argument("--chapters", default=None, help="Path to chapters.json (default: <workdir>/chapters.json)")
    args = parser.parse_args()

    vault_arg = args.vault or os.environ.get("BILIBILI_ANALYZE_VAULT")
    if not vault_arg:
        print("[ERROR] no Obsidian vault specified.")
        print("        Provide --vault /path/to/vault or set the BILIBILI_ANALYZE_VAULT environment variable.")
        sys.exit(1)

    workdir = Path(args.workdir).resolve()
    vault = Path(vault_arg).resolve()

    state_path = workdir / "state.json"
    if not state_path.exists():
        print(f"[ERROR] state.json not found in {workdir}")
        sys.exit(1)
    with open(state_path, encoding="utf-8") as f:
        state = json.load(f)

    meta_path = state.get("metadata_path")
    if meta_path:
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)
    else:
        meta = {}

    chapters_path = Path(args.chapters) if args.chapters else workdir / "chapters.json"
    chapters = []
    if chapters_path.exists():
        with open(chapters_path, encoding="utf-8-sig") as f:
            chapters_raw = json.load(f)
        if isinstance(chapters_raw, dict) and "chapters" in chapters_raw:
            chapters = chapters_raw["chapters"]
        else:
            chapters = chapters_raw
    else:
        print("[WARN] chapters.json not found, note will have no chapter breakdown")

    slug = slugify(meta.get("title", state.get("slug", "untitled")))

    notes_dir = vault / args.notes_dir
    att_dir = vault / args.attachments_dir
    notes_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("  Phase 5: Export to Obsidian")
    print("=" * 50)
    print(f"[INFO] vault: {vault}")
    print(f"[INFO] notes -> {notes_dir}")
    print(f"[INFO] attachments -> {att_dir}")

    assets = copy_assets(workdir, att_dir, slug)

    note = build_note(meta, state, chapters, assets)
    note_path = notes_dir / f"{slug}.md"
    with open(note_path, "w", encoding="utf-8") as f:
        f.write(note)
    print(f"[OK] note -> {note_path} ({len(note)//1024}KB)")
    print("\n[OK] Phase 5 complete.")


if __name__ == "__main__":
    main()
